"""Add offering_type to Offering model

Revision ID: 1cdd746b64c5
Revises: 
Create Date: 2024-11-03 15:26:45.574017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdd746b64c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('attendees')
    with op.batch_alter_table('offering', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offering_type', sa.String(length=20), nullable=False))
        batch_op.alter_column('maximum_capacity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offering', schema=None) as batch_op:
        batch_op.alter_column('maximum_capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('offering_type')

    op.create_table('attendees',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('offering_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'offering_id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password', sa.VARCHAR(length=150), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
